name: Process Airtable Records

on:
  schedule:
    - cron: '0 9-17 * * *'  # Run every hour from 9 AM to 5 PM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  process-records:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run script
      env:
        AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
      run: node process-records.js
